server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: vozni-park-backend

  datasource:
    url: ${DB_URL:}
    username: ${DB_USER:}
    password: ${DB_PASS:}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
